### ISSUE TITLE
Feature request: support additional capabilities

### ISSUE THREAD

**Issue by GoudronViande24** [ctk-hq/ctk#120]
Make it so we can add additional capabilities. It would look like this in a `docker-compose.yml` file: 

```yml
version: "3"

services:
  supercoolservice:
    image: node:latest
    ports:
      - "80:80/tcp"
    environment:
      TZ: 'America/Chicago'
    cap_add:         # THIS
      - NET_ADMIN    # THIS
    restart: unless-stopped
```
